name: build

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019 ]
        python-version: [ 3.8 ]

    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Additional Envs
        shell: bash
        run: |
          echo "PYTHON_SUBVERSION=$(echo $PYTHON_VERSION | cut -c 3-)" >> $GITHUB_ENV
          echo "SINGLE_ACTION_CONFIG=$( [[ $PYTHON_VERSION == 3.8 && $RUNNER_OS == 'macOS' ]] && echo 'True' || echo 'False' )" >> $GITHUB_ENV
          echo "DEPLOY=$( [[ $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF == 'refs/tags'* ]] && echo 'True' || echo 'False' )" >> $GITHUB_ENV        

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
      - shell: msys2 {0}
        run: |
          pacman --noconfirm -S mingw-w64-x86_64-openblas
          pacman --noconfirm -S mingw-w64-x86_64-lapack
          pacman -Ql mingw-w64-x86_64-openblas
          pacman -Ql mingw-w64-x86_64-lapack

      - name: Build wheels
        if: ${{'True' == 'True' || env.DEPLOY == 'True'}}
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD: "cp3${{env.PYTHON_SUBVERSION}}-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
          CIBW_BEFORE_ALL_LINUX: yum install -y openblas-devel
          CIBW_BEFORE_ALL_MACOS: > 
            brew install openblas && 
            cp -r /usr/local/opt/openblas/lib/* /usr/local/lib &&
            cp /usr/local/opt/openblas/include/* /usr/local/include
          CIBW_ENVIRONMENT_WINDOWS: BLAS_LAPACK_LIB_PATHS="C:\\mingw64\\lib;C:\\mingw64\\include\\openblas;C:\\mingw64\\include;C:\\mingw64\\bin"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_COMMAND: pytest {package}
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
        uses: joerick/cibuildwheel@v2.3.1

      - name: Upload artifacts to github
        if: ${{'True' == 'True'}}
        uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
